import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.scss'
import TheHeader from '@/components/TheHeader/TheHeader'
import Providers from '@/components/Providers/Providers'
import StoreProvider from './StoreProvider'
import { Provider } from 'react-redux'

const montserrat = Montserrat({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
	title: 'Book Shop',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>
				<StoreProvider>
					<Providers>
						<TheHeader />
						<main>
							<div className='container'>{children}</div>
						</main>
					</Providers>
				</StoreProvider>
			</body>
		</html>
	)
}
